# Generated by Django 4.2.14 on 2024-07-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAdmin',
        ),
    ]
